services:
  php:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: symfony_php
    volumes:
      - ../:/var/www
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_URL: "mysql://root:rootpassword@mysql:3306/aoetos?serverVersion=8.0&charset=utf8mb4"

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_DATABASE: aoetos
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: symfony_redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"

volumes:
  mysql_data:
